name: Linux VPS Setup (Serveo)

on:
  push: {}
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Install OpenSSH server & client
      - name: Install SSH Server and Client
        run: |
          sudo apt update
          sudo apt install -y openssh-server openssh-client

      # 2. Enable and start SSH
      - name: Enable and Start SSH
        run: |
          sudo systemctl enable ssh
          sudo systemctl start ssh

      # 3. Allow password and root login in sshd_config
      - name: Configure SSH for Password Authentication
        run: |
          sudo sed -i 's/^#PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config
          sudo sed -i 's/^#PermitRootLogin.*/PermitRootLogin yes/'       /etc/ssh/sshd_config
          # If cloud-init created a drop-in, uncomment there too:
          sudo sed -i 's/^#PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config.d/50-cloud-init.conf || true
          sudo systemctl restart ssh

      # 4. Set a password for the built-in 'runner' user
      - name: Set Password for runner
        run: |
          echo "runner:P@ssw0rd!" | sudo chpasswd    # chpasswd reads "user:pass" from stdin :contentReference[oaicite:2]{index=2}

      # 5. Create a reverse SSH tunnel via Serveo and keep the runner alive
      - name: Create SSH Reverse Tunnel (Serveo)
        run: |
          nohup ssh -o StrictHostKeyChecking=no \
                    -o ServerAliveInterval=60 \
                    -o ServerAliveCountMax=3 \
                    -R 0:localhost:22 serveo.net &
          sleep infinity                              # prevent the runner from exiting :contentReference[oaicite:3]{index=3}
