name: Linux VPS Setup with Cloudflare Tunnel

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt remove -y containerd containerd.io docker.io docker-ce || true
          sudo apt install -y --fix-broken wget nmap openssh-server
          # Install cloudflared
          sudo mkdir -p --mode=0755 /usr/share/keyrings
          curl -fsSL https://pkg.cloudflare.com/cloudflare-main.gpg | sudo tee /usr/share/keyrings/cloudflare-main.gpg >/dev/null
          echo 'deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg.cloudflare.com/cloudflared noble main' | sudo tee /etc/apt/sources.list.d/cloudflared.list
          sudo apt update
          if ! sudo apt install -y cloudflared; then
            echo "Falling back to manual cloudflared installation"
            wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
            sudo dpkg -i cloudflared-linux-amd64.deb
            sudo apt install -f -y
          fi
          cloudflared --version
          sudo systemctl start ssh || sudo systemctl start sshd
          sudo systemctl enable ssh || sudo systemctl enable sshd

      - name: Configure SSH Server
        run: |
          echo "=== Configuring SSH ==="
          # Ensure Port 2222 is set
          if grep -q "^Port" /etc/ssh/sshd_config; then
            sudo sed -i 's/^Port .*/Port 2222/' /etc/ssh/sshd_config
          else
            echo "Port 2222" | sudo tee -a /etc/ssh/sshd_config
          fi
          # Ensure PermitRootLogin is set
          if grep -q "^PermitRootLogin" /etc/ssh/sshd_config; then
            sudo sed -i 's/^PermitRootLogin .*/PermitRootLogin yes/' /etc/ssh/sshd_config
          else
            echo "PermitRootLogin yes" | sudo tee -a /etc/ssh/sshd_config
          fi
          # Debug: Show sshd_config
          echo "=== /etc/ssh/sshd_config ==="
          sudo cat /etc/ssh/sshd_config
          # Set root password
          echo "root:P@ssw0rd!" | sudo chpasswd
          # Generate host keys
          sudo ssh-keygen -A
          # Restart SSH service
          sudo systemctl restart ssh || sudo systemctl restart sshd
          sleep 5
          # Check SSHD status
          echo "=== SSHD Status ==="
          sudo systemctl status ssh || sudo systemctl status sshd
          # Check listening port
          echo "=== Listening Ports ==="
          sudo ss -tuln | grep 2222 || echo "SSHD not listening on 2222"

      - name: Show Runner IP
        run: |
          echo "=== Runner External IP ==="
          curl -s https://api.ipify.org || echo "Failed to get external IP"
          echo ""
          echo "=== Runner Internal IP ==="
          ip addr show | grep inet || echo "Failed to get internal IP"

      - name: Verify SSH Server
        run: |
          echo "=== Waiting for SSH server ==="
          for i in {1..6}; do
            sleep 10
            nc -zv localhost 2222 && break || echo "Netcat attempt $i failed"
          done
          echo "=== Nmap Scan ==="
          nmap localhost -p 2222 || echo "Nmap failed"
          echo "=== SSH Test ==="
          for i in {1..3}; do
            ssh -v -p 2222 -o StrictHostKeyChecking=no root@localhost whoami && break || echo "SSH attempt $i failed"
            sleep 5
          done

      - name: Launch Cloudflare Quick Tunnel & Keep Alive
        run: |
          cloudflared tunnel --url ssh://localhost:2222 > tunnel.log 2>&1 &
          sleep 20
          echo "=== Tunnel Endpoint ==="
          grep -Eo 'https://[a-z0-9-]+\.trycloudflare\.com' tunnel.log || cat tunnel.log
          ps aux | grep '[c]loudflared' || echo "No cloudflared process found"
          for i in {1..360}; do
            ps aux | grep '[c]loudflared' || echo "cloudflared process stopped"
            sleep 60
          done
