name: Expose VPS via Serveo

on:
  push:
  workflow_dispatch:

jobs:
  expose-ssh:
    runs-on: ubuntu-latest

    steps:
    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y openssh-server autossh

    - name: Start & Enable SSH
      run: |
        sudo systemctl start ssh
        sudo systemctl enable ssh

    - name: Configure SSH for Password Authentication
      run: |
        sudo sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
        sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
        sudo systemctl restart ssh

    - name: Create vpsuser if Missing
      run: |
        if ! id -u vpsuser >/dev/null 2>&1; then
          sudo useradd -m vpsuser
        fi
        echo "vpsuser:P@ssw0rd!" | sudo chpasswd

    - name: Prepare SSH Known Hosts
      run: |
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        ssh-keyscan -H serveo.net 138.68.79.95 >> ~/.ssh/known_hosts
        chmod 600 ~/.ssh/known_hosts
        cat ~/.ssh/known_hosts  # Debug: Verify known_hosts

    - name: Establish Serveo Reverse SSH Tunnel
      run: |
        autossh -M 0 \
          -o "ServerAliveInterval 60" \
          -o "ServerAliveCountMax 3" \
          -o "StrictHostKeyChecking=yes" \
          -N \
          -R myvps:22:localhost:22 serveo.net &

    - name: Verify Serveo Tunnel
      run: |
        sleep 10
        ps aux | grep autossh
