name: Linux VPS Setup with LocalXpose

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      LOCALXPOSE_AUTH_TOKEN: ${{ secrets.LOCALXPOSE_AUTH_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y wget unzip openssh-server

      - name: Install LocalXpose CLI (Static Binary)
        run: |
          # Download the latest Linux x86_64 client
          wget https://api.localxpose.io/api/v2/downloads/loclx-linux-amd64.zip -O loclx.zip
          unzip loclx.zip
          chmod +x loclx
          sudo mv loclx /usr/local/bin/

      - name: Start & Configure SSH
        run: |
          sudo systemctl start ssh
          sudo systemctl enable ssh
          echo "runneradmin:P@ssw0rd!" | sudo chpasswd
          sudo sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
          sudo systemctl restart ssh

      - name: Authenticate LocalXpose
        run: |
          loclx account login --token "$LOCALXPOSE_AUTH_TOKEN"

      - name: Launch Tunnel & Keep Alive
        run: |
          # Start tunnel in raw mode so it outputs a single-line endpoint, and log it
          loclx tunnel tcp --to 127.0.0.1:22 --raw-mode > tunnel.log 2>&1 &
          sleep 5
          echo "=== Tunnel Endpoint ==="
          # Show the host:port that you can SSH into
          grep -Eo '([a-z0-9]+\.loclx\.io:[0-9]{4,5})' tunnel.log || cat tunnel.log
          # Block indefinitely so the runner (and tunnel) stay up
          sleep infinity
