# .github/workflows/main.yml

name: Linux VPS Setup (Remote.it)

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Server & remote.it CLI
        run: |
          sudo apt update
          sudo apt install -y openssh-server
          # Download and install remote.it CLI (example for Debian/Ubuntu):
          curl -sSL https://downloads.remote.it/software/cli-install.sh | sudo bash

      - name: Configure SSH for Password Auth
        run: |
          echo "runner:P@ssw0rd!" | sudo chpasswd
          sudo sed -i 's/^#PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config
          sudo systemctl restart ssh

      - name: Connect to Remote.it Service
        env:
          RMIT_DEVICE_TOKEN: ${{ secrets.REMOTE_IT_DEVICE_TOKEN }}
        run: |
          remoteit api login --token $RMIT_DEVICE_TOKEN
          remoteit connect --service ssh             # establishes the reverse SSH tunnel
          sleep infinity                             # keep the runner alive
