name: Linux VPS Setup with LocalXpose

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      LOCALXPOSE_AUTH_TOKEN: ${{ secrets.LOCALXPOSE_AUTH_TOKEN }}

    steps:
      - name: Install Dependencies
        run: sudo apt update && sudo apt install -y unzip openssh-server

      - name: Install LocalXpose CLI
        run: sudo npm install -g loclx           # ensures `loclx` is in /usr/local/bin

      - name: Enable SSH Server
        run: |
          sudo systemctl start ssh
          sudo systemctl enable ssh

      - name: Set Default Password
        run: echo "runneradmin:P@ssw0rd!" | sudo chpasswd

      - name: Allow SSH Login
        run: |
          sudo sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
          sudo systemctl restart ssh

      - name: Authenticate LocalXpose
        run: loclx account login --token "$LOCALXPOSE_AUTH_TOKEN"

      - name: Start LocalXpose Tunnel
        run: loclx tunnel tcp --port 22
