name: Linux VPS Setup with LocalXpose

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      LOCALXPOSE_AUTH_TOKEN: ${{ secrets.LOCALXPOSE_AUTH_TOKEN }}  # Access token from your repo's Secrets :contentReference[oaicite:10]{index=10}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install OpenSSH Server
        run: |
          sudo apt update
          sudo apt install -y openssh-server unzip

      - name: Install LocalXpose CLI via npm
        run: npm install -g loclx      # places `loclx` into a PATH’ed folder :contentReference[oaicite:11]{index=11}

      - name: Start & Configure SSH
        run: |
          sudo systemctl start ssh
          sudo systemctl enable ssh
          echo "runneradmin:P@ssw0rd!" | sudo chpasswd
          sudo sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
          sudo systemctl restart ssh

      - name: Authenticate LocalXpose
        run: loclx account login --token "$LOCALXPOSE_AUTH_TOKEN"

      - name: Launch Tunnel & Keep Alive
        run: |
          loclx tunnel tcp --to 127.0.0.1:22 &   # start in background
          sleep 5                                # wait for URL to appear
          echo "Tunnel endpoint:" 
          grep -Eo '([a-z0-9]+\.loclx\.io:[0-9]{4,5})' <(loclx tunnel list)  
          sleep infinity                         # block forever :contentReference[oaicite:12]{index=12}
