name: Linux VPS Setup with LocalXpose

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      LOCALXPOSE_AUTH_TOKEN: ${{ secrets.LOCALXPOSE_AUTH_TOKEN }}

    steps:
      # 1. Checkout code (required for setup-node)
      - uses: actions/checkout@v4

      # 2. Setup Node.js and npm global bin in PATH
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'           # or choose '20', etc. :contentReference[oaicite:11]{index=11}

      # 3. Install SSH server dependencies
      - name: Install SSH Server
        run: |
          sudo apt update
          sudo apt install -y openssh-server unzip

      # 4. Install LocalXpose CLI (choose ONE)
      # ────────────────────────────────────────────────────────────
      # Option A: Snap
      - name: Install LocalXpose via Snap
        run: sudo snap install localxpose      # Official Snap package :contentReference[oaicite:12]{index=12}

      # Option B: npm CLI
      #- name: Install LocalXpose via npm
      #  run: npm install -g loclx              # Official npm package :contentReference[oaicite:13]{index=13}

      # Option C: @localxpose/bin
      #- name: Install LocalXpose via @localxpose/bin
      #  run: npm install @localxpose/bin       # Community wrapper :contentReference[oaicite:14]{index=14}

      # 5. Start and configure SSH
      - name: Enable SSH Server
        run: |
          sudo systemctl start ssh
          sudo systemctl enable ssh

      - name: Set Default Password
        run: echo "runneradmin:P@ssw0rd!" | sudo chpasswd

      - name: Permit Root Login
        run: |
          sudo sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
          sudo systemctl restart ssh

      # 6. Authenticate LocalXpose
      - name: Authenticate LocalXpose
        run: loclx account login --token "$LOCALXPOSE_AUTH_TOKEN"   # Uses non‑interactive login :contentReference[oaicite:15]{index=15}

      # 7. Open TCP Tunnel for SSH
      - name: Start LocalXpose Tunnel
        run: loclx tunnel tcp --port 22                              # Exposes SSH via TCP tunnel :contentReference[oaicite:16]{index=16}
