name: Linux VPS Setup with LocalXpose

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    services:
      ssh-server:
        image: linuxserver/openssh-server
        env:
          PUID: 1000
          PGID: 1000
          USER_NAME: runneradmin
          USER_PASSWORD: P@ssw0rd!
          TZ: Etc/UTC
        ports:
          - 2222:2222
    env:
      LOCALXPOSE_AUTH_TOKEN: ${{ secrets.LOCALXPOSE_AUTH_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y wget unzip nmap

      - name: Install LocalXpose CLI
        run: |
          wget https://api.localxpose.io/api/v2/downloads/loclx-linux-amd64.zip -O loclx.zip
          unzip loclx.zip
          chmod +x loclx
          sudo mv loclx /usr/local/bin/

      - name: Authenticate LocalXpose
        run: |
          loclx account login --token "$LOCALXPOSE_AUTH_TOKEN" || { echo "Authentication failed"; exit 1; }

      - name: Verify SSH Server
        run: |
          nmap ssh-server -p 2222
          ssh -v -p 2222 -o StrictHostKeyChecking=no runneradmin@ssh-server whoami

      - name: Launch Tunnel & Keep Alive
        run: |
          loclx tunnel tcp --to ssh-server:2222 --raw-mode > tunnel.log 2>&1 &
          sleep 15
          echo "=== Tunnel Endpoint ==="
          grep -Eo '([a-z0-9]+\.loclx\.io:[0-9]{4,5})' tunnel.log || cat tunnel.log
          ps aux | grep loclx || echo "No loclx process found"
          sleep infinity
