name: Linux VPS Setup with Cloudflare Tunnel

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    services:
      ssh-server:
        image: linuxserver/openssh-server
        env:
          PUID: 1000
          PGID: 1000
          USER_NAME: runneradmin
          USER_PASSWORD: P@ssw0rd!
          TZ: Etc/UTC
          PASSWORD_ACCESS: "true"
          SUDO_ACCESS: "false"
        ports:
          - 2222:2222

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y wget nmap docker.io

      - name: Show Runner IP
        run: |
          echo "=== Runner External IP ==="
          curl -s https://api.ipify.org
          echo ""
          echo "=== Runner Internal IP ==="
          ip addr show | grep inet

      - name: Debug SSH Server Container
        run: |
          echo "=== Docker Containers ==="
          docker ps -a
          echo "=== SSH Server Logs ==="
          docker logs ssh-server || echo "No logs available"
          echo "=== Network Configuration ==="
          docker inspect ssh-server | grep -i network || echo "No network info"

      - name: Install Cloudflared CLI
        run: |
          sudo mkdir -p --mode=0755 /usr/share/keyrings
          curl -fsSL https://pkg.cloudflare.com/cloudflare-main.gpg | sudo tee /usr/share/keyrings/cloudflare-main.gpg >/dev/null
          echo 'deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg.cloudflare.com/cloudflared focal main' | sudo tee /etc/apt/sources.list.d/cloudflared.list
          sudo apt update
          sudo apt install -y cloudflared
          cloudflared --version

      - name: Verify SSH Server
        run: |
          sleep 30
          echo "=== Resolving ssh-server ==="
          ping -c 4 ssh-server || echo "Ping failed"
          nmap ssh-server -p 2222 || echo "Nmap failed"
          ssh -v -p 2222 -o StrictHostKeyChecking=no runneradmin@ssh-server whoami || echo "SSH test failed, continuing..."

      - name: Launch Cloudflare Quick Tunnel & Keep Alive
        run: |
          cloudflared tunnel --url ssh://ssh-server:2222 > tunnel.log 2>&1 &
          sleep 15
          echo "=== Tunnel Endpoint ==="
          grep -Eo 'https://[a-z0-9-]+\.trycloudflare\.com' tunnel.log || cat tunnel.log
          ps aux | grep '[c]loudflared' || echo "No cloudflared process found"
          for i in {1..360}; do
            ps aux | grep '[c]loudflared' || echo "cloudflared process stopped"
            sleep 60
          done
