name: Expose VPS via Serveo

on:
  push:
  workflow_dispatch:

jobs:
  expose-ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y openssh-server autossh

      - name: Start and Enable SSH
        run: |
          sudo systemctl start ssh
          sudo systemctl enable ssh

      - name: Set Default User and Password
        run: |
          sudo useradd -m runneradmin || true
          echo "runneradmin:P@ssw0rd!" | sudo chpasswd

      - name: Whitelist Serveo Host Key
        run: ssh-keyscan serveo.net >> ~/.ssh/known_hosts

      - name: Establish Serveo Reverse SSH Tunnel
        run: |
          autossh -M 0 \
            -o "ServerAliveInterval 60" \
            -o "ServerAliveCountMax 3" \
            -o "StrictHostKeyChecking=no" \
            -N \
            -R myvps:22:localhost:22 serveo.net
