name: Linux VPS Setup (localhost.run)

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Dependencies
      run: |
        sudo apt update \
          && sudo apt install -y wget unzip openssh-server openssh-client

    - name: Enable SSH Server
      run: |
        sudo systemctl start ssh \
          && sudo systemctl enable ssh

    - name: Set Default Password
      run: echo "runneradmin:P@ssw0rd!" | sudo chpasswd

    - name: Allow Password SSH Login
      run: |
        sudo sed -i 's/^#PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config \
        && sudo sed -i 's/^#PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config \
        && sudo systemctl restart ssh

  - name: Create SSH Reverse Tunnel via localhost.run
  run: |
    ssh -o StrictHostKeyChecking=no \
        -o ServerAliveInterval=60 \
        -o ServerAliveCountMax=3 \
        -R 0:localhost:22 nokey@ssh.localhost.run
