name: Linux VPS Setup with LocalXpose

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Dependencies
      run: sudo apt update && sudo apt install -y wget unzip openssh-server

    - name: Download LocalXpose
      run: wget https://localxpose.io/releases/localxpose-linux-amd64.zip -O localxpose.zip

    - name: Extract LocalXpose
      run: unzip localxpose.zip && chmod +x lx

    - name: Authenticate LocalXpose
      run: ./lx auth ${{ secrets.LOCALXPOSE_AUTH_TOKEN }}

    - name: Enable SSH Server
      run: sudo systemctl start ssh && sudo systemctl enable ssh

    - name: Set Default Password
      run: echo "runneradmin:P@ssw0rd!" | sudo chpasswd

    - name: Allow SSH Login
      run: |
        sudo sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
        sudo systemctl restart ssh

    - name: Create Tunnel using LocalXpose
      run: ./lx tunnel tcp --port 22
