name: Expose VPS via Serveo

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours

jobs:
  expose-ssh:
    runs-on: ubuntu-latest

    steps:
    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y openssh-server autossh sshpass

    - name: Start & Enable SSH
      run: |
        sudo systemctl start ssh
        sudo systemctl enable ssh
        sudo systemctl status ssh --no-pager  # Debug: Check SSH service status
        # Debug: Verify SSH port is listening
        sudo netstat -tuln | grep :22 || exit 1

    - name: Configure SSH for Password Authentication
      run: |
        sudo sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
        sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
        sudo systemctl restart ssh

    - name: Create vpsuser if Missing
      env:
        VPS_PASSWORD: ${{ secrets.VPS_PASSWORD }}
      run: |
        if [ -z "$VPS_PASSWORD" ]; then
          echo "Error: VPS_PASSWORD secret is not set or is empty"
          exit 1
        fi
        if ! id -u vpsuser >/dev/null 2>&1; then
          sudo useradd -m vpsuser
        fi
        echo "vpsuser:$VPS_PASSWORD" | sudo chpasswd
        # Debug: Verify user creation
        id vpsuser || exit 1

    - name: Test Local SSH Login
      env:
        VPS_PASSWORD: ${{ secrets.VPS_PASSWORD }}
      run: |
        sshpass -p "$VPS_PASSWORD" ssh -o StrictHostKeyChecking=no vpsuser@localhost whoami || exit 1

    - name: Prepare SSH Known Hosts
      run: |
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        ssh-keyscan -H serveo.net >> ~/.ssh/known_hosts
        chmod 600 ~/.ssh/known_hosts
        cat ~/.ssh/known_hosts  # Debug: Verify known_hosts

    - name: Establish Serveo Reverse SSH Tunnel
      run: |
        # Run autossh with verbose output and log to file
        autossh -M 0 \
          -v \
          -o "ServerAliveInterval 60" \
          -o "ServerAliveCountMax 3" \
          -o "StrictHostKeyChecking=yes" \
          -N \
          -R myvps:22:localhost:22 serveo.net > autossh.log 2>&1 &
        # Debug: Wait and check autossh
        sleep 10
        ps aux | grep autossh || exit 1
        cat autossh.log  # Debug: Show autossh output

    - name: Keep Job Running and Verify Tunnel
      run: |
        sleep 30  # Wait longer for tunnel to stabilize
        ps aux | grep autossh  # Verify autossh is running
        # Debug: Check tunnel status multiple times
        for i in {1..3}; do
          echo "Tunnel check attempt $i:"
          curl -s -I http://myvps.serveo.net || echo "Warning: Tunnel may not be active"
          sleep 5
        done
        echo "Keeping job alive to maintain Serveo tunnel..."
        sleep infinity
