name: Linux VPS Setup with Cloudflare Tunnel

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt remove -y containerd containerd.io || true
          sudo apt install -y --fix-broken wget nmap openssh-server cloudflared
          sudo systemctl start ssh
          sudo systemctl enable ssh

      - name: Configure SSH Server
        run: |
          echo "=== Configuring SSH ==="
          sudo sed -i 's/#Port 22/Port 2222/' /etc/ssh/sshd_config
          sudo sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
          echo "root:P@ssw0rd!" | sudo chpasswd
          sudo ssh-keygen -A
          sudo systemctl restart ssh
          sleep 5
          sudo ss -tuln | grep 2222 || echo "SSHD not listening on 2222"

      - name: Show Runner IP
        run: |
          echo "=== Runner External IP ==="
          curl -s https://api.ipify.org || echo "Failed to get external IP"
          echo ""
          echo "=== Runner Internal IP ==="
          ip addr show | grep inet || echo "Failed to get internal IP"

      - name: Verify SSH Server
        run: |
          echo "=== Waiting for SSH server ==="
          for i in {1..6}; do
            sleep 10
            nc -zv localhost 2222 && break || echo "Netcat attempt $i failed"
          done
          echo "=== Nmap Scan ==="
          nmap localhost -p 2222 || echo "Nmap failed"
          echo "=== SSH Test ==="
          for i in {1..3}; do
            ssh -v -p 2222 -o StrictHostKeyChecking=no root@localhost whoami && break || echo "SSH attempt $i failed"
            sleep 5
          done

      - name: Launch Cloudflare Quick Tunnel & Keep Alive
        run: |
          cloudflared tunnel --url ssh://localhost:2222 > tunnel.log 2>&1 &
          sleep 20
          echo "=== Tunnel Endpoint ==="
          grep -Eo 'https://[a-z0-9-]+\.trycloudflare\.com' tunnel.log || cat tunnel.log
          ps aux | grep '[c]loudflared' || echo "No cloudflared process found"
          for i in {1..360}; do
            ps aux | grep '[c]loudflared' || echo "cloudflared process stopped"
            sleep 60
          done
