name: Linux VPS Setup (Serveo)

on:
  push: {}
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH Server and Client
        run: |
          sudo apt update
          sudo apt install -y openssh-server openssh-client

      - name: Enable and Start SSH
        run: |
          sudo systemctl enable ssh
          sudo systemctl start ssh

      - name: Set Password for runner
        run: echo "runner:P@ssw0rd!" | sudo chpasswd

      - name: Create SSH Reverse Tunnel (Serveo)
        run: |
          nohup ssh -o StrictHostKeyChecking=no \
                    -o ServerAliveInterval=60 \
                    -o ServerAliveCountMax=3 \
                    -R 0:localhost:22 serveo.net &
          sleep infinity
