name: Linux VPS Setup with Cloudflare Tunnel

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    services:
      ssh-server:
        image: rastasheep/ubuntu-sshd:18.04
        env:
          ROOT_PASSWORD: P@ssw0rd!
        ports:
          - 2222:22
        options: --health-cmd "nc -z localhost 22 || exit 1" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt remove -y containerd containerd.io || true
          sudo apt install -y --fix-broken wget nmap docker.io jq
          sudo systemctl start docker
          sudo systemctl enable docker

      - name: Show Runner IP
        run: |
          echo "=== Runner External IP ==="
          curl -s https://api.ipify.org || echo "Failed to get external IP"
          echo ""
          echo "=== Runner Internal IP ==="
          ip addr show | grep inet || echo "Failed to get internal IP"

      - name: Debug SSH Server Container
        run: |
          echo "=== Docker Containers ==="
          docker ps -a || echo "Docker ps failed"
          echo "=== SSH Server Logs ==="
          docker logs ssh-server || echo "No logs available"
          echo "=== Container Network ==="
          docker inspect ssh-server | jq -r '.[] | .NetworkSettings.IPAddress' || echo "No IP address found"
          echo "=== Container Ports ==="
          docker inspect ssh-server | jq -r '.[] | .NetworkSettings.Ports' || echo "No port info"
          echo "=== Health Status ==="
          docker inspect ssh-server | jq -r '.[] | .State.Health.Status' || echo "No health status"

      - name: Verify SSH Server
        run: |
          echo "=== Waiting for SSH server ==="
          for i in {1..6}; do
            sleep 10
            nc -zv localhost 2222 && break || echo "Netcat attempt $i failed"
          done
          echo "=== Nmap Scan ==="
          nmap localhost -p 2222 || echo "Nmap failed"
          echo "=== SSH Test ==="
          for i in {1..3}; do
            ssh -v -p 2222 -o StrictHostKeyChecking=no root@localhost whoami && break || echo "SSH attempt $i failed"
            sleep 5
          done

      - name: Install Cloudflared CLI
        run: |
          sudo mkdir -p --mode=0755 /usr/share/keyrings
          curl -fsSL https://pkg.cloudflare.com/cloudflare-main.gpg | sudo tee /usr/share/keyrings/cloudflare-main.gpg >/dev/null
          echo 'deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg.cloudflare.com/cloudflared focal main' | sudo tee /etc/apt/sources.list.d/cloudflared.list
          sudo apt update
          sudo apt install -y cloudflared
          cloudflared --version

      - name: Launch Cloudflare Quick Tunnel & Keep Alive
        run: |
          cloudflared tunnel --url ssh://localhost:2222 > tunnel.log 2>&1 &
          sleep 20
          echo "=== Tunnel Endpoint ==="
          grep -Eo 'https://[a-z0-9-]+\.trycloudflare\.com' tunnel.log || cat tunnel.log
          ps aux | grep '[c]loudflared' || echo "No cloudflared process found"
          for i in {1..360}; do
            ps aux | grep '[c]loudflared' || echo "cloudflared process stopped"
            sleep 60
          done
